# -*- coding: utf-8 -*-
"""d001

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ILGzgUrPKo_nnQ6UuwPrCYFG2ouu4biS
"""

# Curso em Vídeo de Python - Professor Gustavo Guanabara
# Aluno: Anderson Costa

# Desafio 001: Crie um script Python que leia o nome de uma pessoa e mostre uma mensagem de boas-vindas de acordo com o valor digitado.

nome = input('Digite seu nome: ')
print('Olá ' + nome + '! Prazer em te conhecer!')