# -*- coding: utf-8 -*-
"""d002

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11L9-zT105Ugq_4PboYkEGsBJ3K07g5go
"""

# Curso em Vídeo de Python - Professor Gustavo Guanabara
# Aluno: Anderson Costa

# Desafio 002: Crie um script Python que leia o dia, o mês e o ano de nascimento de uma pessoa e mostre uma mensagem com a data formatada.

nome = input('Nome: ')
dia = input('Dia: ')
mes = input('Mês: ')
ano = input('Ano: ')
print('Oi ' + nome + '! Você nasceu no dia ' + dia + ' de ' + mes + ' de ' + ano + '. Correto?')