# -*- coding: utf-8 -*-
"""d003

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qm6t-nmPXpzyTLgkil4dwm2KhLyaOO-1
"""

# Curso em Vídeo de Python - Professor Gustavo Guanabara
# Aluno: Anderson Costa

# Desafio 003: Crie um script Python que leia dois números e tente mostrar a soma entre eles.

num1 = int(input('Primeiro número: '))
num2 = int(input('Segundo número: '))
print('A soma de {} com {} é igual a {}.'.format(num1, num2, num1+num2))