# -*- coding: utf-8 -*-
"""d004

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eIB0UOMKnmBxx_efcnqXJEweV1LNRBmV
"""

# Curso em Vídeo de Python - Professor Gustavo Guanabara
# Aluno: Anderson Costa

# Desafio 004: Faça um programa que leia algo pelo teclado e mostre na tela o seu tipo primitivo e todas as informações possíveis sobre ele.

var = input('Digite algo no teclado: ')
print('O tipo primitivo é {}'.format(type(var)))
print('Você digitou algo numérico? {}'.format(var.isnumeric()))
print('Você digitou algo alfabético? {}'.format(var.isalpha()))
print('Você digitou algo alfanumérico? {}'.format(var.isalnum()))
print('Você digitou tudo em MAIÚSCULO? {}'.format(var.isupper()))
print('Você digitou tudo em minúsculo? {}'.format(var.islower()))