# -*- coding: utf-8 -*-
"""d005

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/171ikAojLabBbBLMsycIb7PQz1OoyCZVS
"""

# Curso em Vídeo de Python - Professor Gustavo Guanabara
# Aluno: Anderson Costa

# Desafio 005: Faça um programa que leia um número inteiro e mostre na tela o seu antecessor e seu sucessor.

num = int(input('Digite um número inteiro: '))
print(f'O antecessor é {num-1} e o sucessor é {num+1}.')