# -*- coding: utf-8 -*-
"""d006

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ftk6W2vvNZmj7NLAJE1QKtPk5mTEqbbL
"""

# Curso em Vídeo de Python - Professor Gustavo Guanabara
# Aluno: Anderson Costa

# Desafio 006: Crie um algoritmo que leia um número e mostre o seu dobro, triplo e raiz quadrada.

num = float(input('Digite um número: '))
print(f'O dobro é {2*num:.2f}, o triplo é {3*num:.2f} e a raiz quadrada é {num**(1/2):.2f}.')