# -*- coding: utf-8 -*-
"""d007

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EISPvl-h6AOg3bGa4MMjocziBlFJGF34
"""

# Curso em Vídeo de Python - Professor Gustavo Guanabara
# Aluno: Anderson Costa

# Desafio 007: Desenvolva um programa que leia as duas notas de um aluno, calcule e mostre sua média.

nota1 = float(input('Nota Parcial: '))
nota2 = float(input('Nota Global: '))
media = (nota1 + nota2)/2

print(f'A média do aluno é {media:.1f}.')