# -*- coding: utf-8 -*-
"""d008

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uQ-l4svMeYLFJfn7Lt83tDIMaGJn0TUH
"""

# Curso em Vídeo de Python - Professor Gustavo Guanabara
# Aluno: Anderso Costa

# Desafio 008: Escreva um programa que leia um valor em metros e exiba convertido em centímetros e milímetros.

m = float(input('Insira uma medida em metros: '))
print(f'A medida {m:.2f} m (metros) corresponde a {100*m:.2f} cm (centímetros) e a {1000*m:.2f} mm (milímetros).')