# -*- coding: utf-8 -*-
"""d009

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1G_TTZjc1l66shZO6cXOpLdb5DpVvaORO
"""

# Curso em Vídeo de Python - Professor Gustavo Guanabara
# Aluno: Anderson Costa

# Desafio 009: Faça um programa que leia um número inteiro qualquer e mostre na tela a sua tabuada.

num = int(input('Insira um número inteiro: '))
print(f'\nTABUADA DO {num}')
print(12*'-')
print(f'{num} X {1:2} = {1*num}')
print(f'{num} X {2:2} = {2*num}')
print(f'{num} X {3:2} = {3*num}')
print(f'{num} X {4:2} = {4*num}')
print(f'{num} X {5:2} = {5*num}')
print(f'{num} X {6:2} = {6*num}')
print(f'{num} X {7:2} = {7*num}')
print(f'{num} X {8:2} = {8*num}')
print(f'{num} X {9:2} = {9*num}')
print(f'{num} X {10} = {10*num}')
print(12*'-')