# -*- coding: utf-8 -*-
"""d010

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12GZLS3fTxkh3iQ7aqZ1lyi2SX8JezLz4
"""

# Curso em Vídeo de Python - Professor Gustavo Guanabara
# Aluno: Anderson Costa

# Desafio 010: Crie um programa que leia quanto dinheiro uma pessoa tem na carteira e mostre quantos dólares ela pode comprar.
# Considere US$ 1,00 = R$ 5,25.

real = float(input('Quanto dinheiro você tem na carteira? R$ '))
print(f'Com R$ {real:.2f} você consegue comprar US$ {real/5.25:.2f}.')