# -*- coding: utf-8 -*-
"""d011

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KQH4pyCwiavDEEjX8m_HcE3ULwmzKvUb
"""

# Curso em Vídeo de Python - Professor Gustavo Guanabara
# Aluno: Anderson Costa

# Desafio 011: Faça um programa que leia a largura e a altura de uma parede em metros, calcule a sua área e a quantidade
# de tinta necessária para pintá-la, sabendo que cada litro de tinta pinta uma área de 2 metros quadrados.

l = float(input('Largura da parede (metros): '))
h = float(input('Altura da parede (metros): '))

print(f'A área da parede é {l*h} m². São necessários então {(l*h)/2} litros de tinta para pintá-la.')