# -*- coding: utf-8 -*-
"""d012

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fOyg6gPF7SrZkDKzYxmCmFQzN_QC2CmA
"""

# Curso em Vídeo de Python - Professor Gustavo Guanabara
# Aluno: Anderson Costa

# Desafio 012: Faça um algoritmo que leia o preço de um produto e mostre seu novo preço, com 5% de desconto.

preço = float(input('Qual o preço do produto? R$ '))
print(f'Com 5% de desconto o preço final do produto é R$ {preço*0.95:.2f}.')