# -*- coding: utf-8 -*-
"""d013

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11TLMOVuC1pjDfa4-FUfd7v9VTyiyqckr
"""

# Curso em Vídeo de Python - Professor Gustavo Guanabara
# Aluno: Anderson Costa

# Desafio 013: Faça um algoritmo que leia o salário de um funcionário e mostre o seu novo salário com 15% de aumento.

salário = float(input('Qual o salário do funcionário? R$ '))
print(f'Com o aumento de 15% o novo salário do funcionário é no valor de R$ {salário*1.15:.2f}')