# -*- coding: utf-8 -*-
"""d014

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/150bvrUFlEdvllUmW19ZpDdexY61CLk02
"""

# Curso em Vídeo de Python - Professor Gustavo Guanabara
# Aluno: Anderson Costa

# Desafio 014: Escreva um programa que converta uma temperatura digitada em °C e converta para °F.

tC = float(input('Informa a temperatura em °C? '))
tF = (tC*9)/5 + 32
tK = tC + 273.15
print(f'A temperatura de {tC:.1f} °C(Celsius) corresponde a {tF:.1f} °F(Fahrenheit) ou {tK:.2f} K(Kelvin).')