# -*- coding: utf-8 -*-
"""d017

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1u4o-DNbixpCf3cX4YnuV4neohx8ewnRK
"""

# Curso em Vídeo de Python - Professor Gustavo Guanabara
# Aluno: Anderson Costa

# Desafio 017: Faça um programa que leia o comprimento do cateto oposto e do cateto adjacente
# de um triângulo retângulo, calcule e mostre o comprimento da hipotenusa.

from math import sqrt, pow, hypot

co = float(input('Medida do Cateto Oposto: '))
ca = float(input('Medida do Cateto Adjacente: '))
h = sqrt(pow(co, 2) + pow(ca, 2))

# h = hypot(co, ca)

print(f'\nA medida da Hipotenusa é {h:.2f}.')