# -*- coding: utf-8 -*-
"""d019

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fxipP1xzYS6-pMNyTp0ozHFI6oC5e9O5
"""

# Curso em Vídeo de Python - Professor Gustavo Guanabara
# Aluno: Anderson Costa

# Desafio 019: Um professor quer sortear um dos seus quatro alunos para apagar o quadro.
# Faça um programa que ajude ele, lendo o nome deles e escrevendo o nome do escolhido.

from random import choice

p1 = input('Primeiro Aluno: ')
p2 = input('Segundo Aluno: ')
p3 = input('Terceiro Aluno: ')
p4 = input('Quarto Aluno: ')

print(f'\nO aluno sorteado para apagar o quadro foi: {choice([p1, p2, p3, p4])}')