# -*- coding: utf-8 -*-
"""d022.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MJmSwkamrbJYSB2S-3EjzV7LBSDQNZRk
"""

# Curso em Vídeo de Python - Professor Gustavo Guanabara
# Aluno: Anderson Costa

# Desafio 022: Crie um programa que leia o nome completo de uma pessoa e mostre:
# (a) O nome com todas as letras maiúsculas.
# (b) O nome com todas as letras minúsculas.
# (c) Quantas letras ao todo, sem contar os espaços.
# (d) Quantas letras tem o primeiro nome.

nome = input('Insira seu nome completo: ')

# Tratamento da String
words = nome.split()
nome = ' '.join(words)

# Quantidade de Letras
letras = len(nome) - nome.count(' ')

print(f'Seu nome em MAIÚSCULO é: {nome.upper()}.')
print(f'Seu nome em minúsculo é: {nome.lower()}.')
print(f'Seu nome completo tem {letras} letras.')
print(f'Seu primeiro nome tem {len(nome.split()[0])} letras.')