# -*- coding: utf-8 -*-
"""d023.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bvMQvSkSLma4elyfRJkgzWbLGwFpFJOv
"""

# Curso em Vídeo de Python - Professor Gustavo Guanabara
# Aluno: Anderson Costa

# Desafio 023: Faça um programa que leia um número de 0 à 9999 e mostre na tela cada
# um dos seus dígitos separados. Unidade: Dezena: Centena: Milhar:

n = int(input('Digite um número de 0 à 9999: '))

U = (n // 1) % 10
D = (n // 10) % 10
C = (n // 100) % 10
M = (n // 1000) % 10

print(f'Unidades: {U}')
print(f'Dezenas:  {D}')
print(f'Centenas: {C}')
print(f'Milhares: {M}')