# -*- coding: utf-8 -*-
"""d024

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tLGrMi8vzvcaOGFvk40nDhW3GQm4hws-
"""

# Curso em Vídeo de Python - Professor Gustavo Guanabara
# Aluno: Anderson Costa

# Desafio 024: Crie um programa que leia o nome de uma cidade e diga se ela começa
# ou não com o nome "SANTO".

city = input('Informe o nome da cidade: ')

# Tratamento da String
city = city.upper().strip()

print(f'\nA cidade informada começa com nome SANTO? {city.split()[0] == "SANTO"}')