# -*- coding: utf-8 -*-
"""d025

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IYk_uSAj6xPXi8wiFn3NJphLZpVT_NZf
"""

# Curso em Vídeo de Python - Professor Gustavo Guanabara
# Aluno: Anderson Costa

# Desafio 025: Crie um programa que leia o nome de uma pessoa e diga se ela tem "Silva" no nome.

nome = input('Digite seu nome completo: ')

# Tratamento da String
nome = nome.strip().title()

print(f'\nO seu nome tem Silva? {"Silva" in nome}')