# -*- coding: utf-8 -*-
"""d026

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/142Ih_lkzlRRciMOYub2UA_fpY3OYQXzw
"""

# Curso em Vídeo de Python - Professor Gustavo Guanabara
# Aluno: Anderson Costa

# Desafio 026: Faça um programa que leia uma frase pelo teclado e mostre:
# (a) Quantas vezes aparece a letra A.
# (b) Em que posição ela aparece a primeira vez.
# (c) Em que posição ela aparece a última vez.

frase = input('Insira uma frase pelo teclado: ')

# Tratamento
frase = frase.upper().strip()
frase.replace('Á','A')
frase.replace('Ã','A')
rev = frase[len(frase)::-1]

print(f'\nA letra A aparece {frase.count("A")} vezes nesta frase.')
print(f'\nA letra A aparece pela primeira vez na posição {frase.find("A")+1}.')
print(f'\nA letra A aparece pela última vez na posição {len(frase) - rev.find("A")}.')