# -*- coding: utf-8 -*-
"""d027

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15_nY6lZZmX_8UAE4ufsSnPOAdjjoUML8
"""

# Curso em Vídeo de Python - Professor Gustavo Guanabara
# Aluno: Anderson Costa

# Desafio 027: Faça um programa que leia o nome completo de uma pessoa, mostrando
# em seguida o primeiro e o último nome separadamente.
# Exemplo: Ana Maria de Souza --> Ana Souza

nome = str(input('Digite seu nome completo: ')).title()

print(f'\nSeu nome reduzido é {nome.split()[0]} {nome.split()[-1]}.')