# -*- coding: utf-8 -*-
"""d030

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/180OFV6wjgN2Iq-vq4LqVFvLqXqG0eOc4
"""

# Curso em Vídeo de Python - Professor Gustavo Guanabara
# Aluno: Anderson Costa

# Desafio 030: Crie um programa que leia um número inteiro e mostre na tela se
# ele é PAR ou ÍMPAR.

num = int(input('Insira um número inteiro: '))
print('\nNúmero PAR.' if num%2==0 else '\nNúmero ÍMPAR.')