# -*- coding: utf-8 -*-
"""d032

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RXhrte46gBRyE0o571Hn26fyybFUo6qL
"""

# Curso em Vídeo de Python - Professor Gustavo Guanabara
# Aluno: Anderson Costa

# Desafio 032: Faça um programa que leia um ano qualquer e mostre se ele é Bissexto.

from datetime import date

year = int(input('Insira um ano qualquer ou digite 0 para o ano atual: '))

if year == 0:
  year = date.today().year

# Para que um ano seja considerado BISSEXTO, ele deve ser divisível por 4, exceto os
# múltiplos de 100 que não são múltiplos de 400.

if (year%4 == 0 and year%100 != 0) or year%400 == 0:
  print(f'\nO ano {year} é BISSEXTO!!!')
else:
  print(f'\n O ano {year} não é BISSEXTO!!!')