# -*- coding: utf-8 -*-
"""d033

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Wiu0UERgvV0LvMDPSZ-YR2_zo83kbO5d
"""

# Curso em Vídeo de Python - Professor Gustavo Guanabara
# Aluno: Anderson Costa

# Desafio 033: Faça um programa que leia três números e mostre qual é o MAIOR e o MENOR.

n1 = int(input('Primeiro número: '))
n2 = int(input('Segundo número:  '))
n3 = int(input('Terceiro número: '))

M = n1  # MAIOR
m = n1  # MENOR

# Descobrindo o MAIOR
if (M < n2):
  M = n2
if (M < n3):
  M = n3

# Descobrindo o MENOR
if (m > n2):
  m = n2
if (m > n3):
  m = n3

print(f'\nO MAIOR número é {M} e o MENOR é {m}.')