# -*- coding: utf-8 -*-
"""d035

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fwXjkoOkoHeZXHIaPNSvNxnCID4_Ppzf
"""

# Curso em Vídeo de Python - Professor Gustavo Guanabara
# Aluno: Anderson Costa

# Desafio 035: Desenvolva um programa que leia o comprimento de três retas
# e diga ao usuário se elas podem ou não formar um triângulo.

r1 = float(input('Medida da RETA 1: '))
r2 = float(input('Medida da RETA 2: '))
r3 = float(input('Medida da RETA 3: '))

if (abs(r2-r3) < r1 and r1 < (r2+r3)) and (abs(r1-r3) < r2 and r2 < (r1+r3)) and (abs(r1-r2) < r3 and r3 < (r1+r2)):
  print(f'\nAs retas com medidas {r1}cm, {r2}cm e {r3}cm podem formar um triângulo!')
else:
  print(f'\nAs retas com medidas {r1}cm, {r2}cm e {r3}cm NÃO podem formar um triângulo!')