# -*- coding: utf-8 -*-
"""d036

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JyqDGP5PlEmpGohIso7Y_14nnjfC3-LA
"""

# Curso em Vídeo de Python - Professor Gustavo Guanabara
# Aluno: Anderson Costa

# Desafio 036: Escreva um programa para aprovar o empréstimo bancário para
# a compra de uma casa. O programa vai perguntar o valor da casa, o salário
# do comprador e em quantos anos ele vai pagar.
#   Calcule o valor da prestação mensal, sabendo que ele não pode exceder 30%
# do salário ou então o empréstimo será negado.

valor_casa = float(input('Valor da Casa: R$ '))
sal_comp = float(input('Salário do Comprador: R$ '))
t = float(input('Tempo de Pagamento: '))

# Cálculo das Parcelas
parc = valor_casa / (12*t)

if parc > 0.3*sal_comp:
  print(f'\nEmpréstimo NEGADO!!! As parcelas do imóvel são de R${parc:.2f}, que excede 30% do salário do Comprador.')
else:
  print(f'\nEmpréstimo APROVADO!!! As parcelas do imóvel são de R${parc:.2f}, que é compatível com o salário do Comprador.')