# -*- coding: utf-8 -*-
"""d037

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Hkso1rBk_kV93Up_8B1vUMKVjj357OFc
"""

# Curso em Vídeo de Python - Professor Gustavo Guanabara
# Aluno: Anderson Costa

# Desafio 037: Escreva um programa que leia um número inteiro qualquer
# e peça para o usuário escolher qual será a base de conversão:
# [1] - Binário [2] - Octal [3] - Hexadecimal

n = int(input('Insira um número inteiro: '))

print('\n [1] - Binário \n [2] - Octal \n [3] - Hexadecimal \n')
base = int(input('Selecione a Base de Conversão: '))

if base == 1:
  print(f'\nO número {n} na base BINÁRIA é {bin(n)[2:]}.')
elif base == 2:
  print(f'\nO número {n} na base OCTAL é {oct(n)[2:]}.')
elif base == 3:
  print(f'\nO número {n} na base HEXADECIMAL é {hex(n)[2:]}.')
else:
  print('\nBase INVÁLIDA!!!')