# -*- coding: utf-8 -*-
"""d038

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Cn5JPDVGV1hSjb3_79CVtkgks6hQ-Tce
"""

# Curso em Vídeo de Python - Professor Gustavo Guanabara
# Aluno: Anderson Costa

# Desafio 038: Escreva um programa que leia dois números inteiros e compare-os,
# mostrando na tela uma mensagem:
# - O primeiro valor é maior.
# - O segundo valor é maior.
# - Não existe valor maior, os dois são iguais.

n1 = int(input('Primeiro número inteiro: '))
n2 = int(input('Segundo número inteiro: '))

if n1 > n2:
  print('\nO primeiro valor é maior!')
elif n1 < n2:
  print('\nO segundo valor é maior!')
else:
  print('\nNão existe valor maior, os dois são iguais!')