# -*- coding: utf-8 -*-
"""d039

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1A9KcjTW37dkKpTH-bKN5zJXNtjQYX4sg
"""

# Curso em Vídeo de Python - Professor Gustavo Guanabara
# Aluno: Anderson Costa

# Desafio 039: Faça um programa que leia o ano de nascimento de um jovem
# e informe, de acordo com sua idade:
# - Se ele ainda vai se alistar ao serviço militar.
# - Se é a hora de se alistar.
# - Se já passou do tempo do alistamento.

from datetime import date

ano_hoje = date.today().year

ano_nasc = int(input('Ano de Nascimento: '))

idade = ano_hoje - ano_nasc

if idade < 18:
  print(f'\nCom {idade} anos, ainda faltam {18-idade} anos para se alistar ao serviço militar!')
elif idade == 18:
  print(f'\nCom {idade} anos, já está na hora de se alistar ao serviço militar!')
else:
  print(f'\nCom {idade} anos, já passaram {idade-18} anos do seu alistamento ao serviço militar!')