# -*- coding: utf-8 -*-
"""d040

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_8gVIQwhA3m8xupI06mF2-HYXI6ouXVQ
"""

# Curso em Vídeo de Python - Professor Gustavo Guanabara
# Aluno: Anderson Costa

# Desafio 040: Crie um programa que leia duas notas de um aluno e calcule sua média,
# mostrando uma mensagem no final, de acordo com a média atingida:
# - Média abaixo de 5.0: REPROVADO
# - Média entre 5.0 e 6.9: RECUPERAÇÃO
# - Média 7.0 ou superior: APROVADO

n1 = float(input('Primeira nota: '))
n2 = float(input('Segunda nota: '))

md = (n1 + n2)/2

if md < 5.0:
  print(f'\nMédia {md:.1f} \nAluno REPROVADO!!!')
elif md >= 5.0 and md <= 6.9:
  print(f'\nMédia {md:.1f} \nAluno de RECUPERAÇÃO!!!')
else:
  print(f'\nMédia {md:.1f} \nAluno APROVADO!!!')