# -*- coding: utf-8 -*-
"""d041

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hncMbp1vdjrVLZlylx0i2L28Gwke99uD
"""

# Curso em Vídeo de Python - Professor Gustavo Guanabara
# Aluno: Anderson Costa

# Desafio 041: A confederação nacional de natação precisa de um programa que
# leia o ano de nascimento de um atleta e mostre sua categoria:
# - Até 9 anos: MIRIM
# - Até 14 anos: INFANTIL
# - Até 19 anos: JÚNIOR
# - Até 20 anos: SÊNIOR
# - Acima de 20 anos: MASTER

from datetime import date

ano_atual = date.today().year

ano_nasc = int(input('Ano de Nascimento: '))

idade = ano_atual - ano_nasc

if idade <= 9:
  print(f'\nCom {idade} anos. Categoria MIRIM.')
elif idade > 9 and idade <= 14:
  print(f'\nCom {idade} anos. Categoria INFANTIL.')
elif idade > 14 and idade <= 19:
  print(f'\nCom {idade} anos. Categoria JÚNIOR.')
elif idade == 20:
  print(f'\nCom {idade} anos. Categoria SÊNIOR.')
else:
  print(f'\nCom {idade} anos. Categoria MASTER.')