# -*- coding: utf-8 -*-
"""d044

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zMZv2GH1BGKcHG-41j3m6nmYCvRR4UwT
"""

# Curso em Vídeo de Python - Professor Gustavo Guanabara
# Aluno: Anderson Costa

# Desafio 044: Elabore um programa que calcule o valor a ser pago por um produto,
# considerando o seu preço normal e a condição de pagamento:
# - À vista (Dinheiro ou Cheque): 10% de desconto
# - À vista (Cartão): 5% de desconto
# - Em até 2x no Cartão: Preço Normal
# - Em 3x ou mais no Cartão: 20% de Juros

preço = float(input('Preço do Produto: R$ '))

print('\n[1] - À vista (Dinheiro ou Cheque) \n[2] - À vista (Cartão) \n[3] - Em até 2x no Cartão \n[4] - Em 3x ou mais no Cartão\n')

forma = int(input('Selecione a Forma de Pagamento: '))

if forma == 1:
  print(f'\nPagando à vista no Dinheiro ou Cheque, o valor do produto é R${preço-0.1*preço:.2f}')
elif forma == 2:
  print(f'\nPagando à vista no Cartão, o valor do produto é R${preço-0.05*preço:.2f}')
elif forma == 3:
  print(f'\nPagando em até 2x no Cartão, o valor do produto é R${preço:.2f}')
elif forma == 4:
  print(f'\nPagando em 3x ou mais no Cartão, o valor do produto é R${preço+0.2*preço:.2f}')
else:
  print('\nForma de Pagamento inválida! Tente novamente!!!')