# -*- coding: utf-8 -*-
"""d045

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jKGCqXwVhNeTwp4KX_NCLM0xVMRJ87vK
"""

# Curso em Vídeo de Python - Professor Gustavo Guanabara
# Aluno: Anderson Costa

# Desafio 045: Crie um programa que faça o computador jogar JOKEMPÔ com você.

from random import choice
from time import sleep

lista = ['PEDRA', 'PAPEL', 'TESOURA']

cpu = choice(lista)

print('\n[1] - PEDRA \n[2] - PAPEL \n[3] - TESOURA\n')

player = int(input('Escolha sua jogada: '))

if player == 1:
  player = 'PEDRA'
elif player == 2:
  player = 'PAPEL'
else:
  player = 'TESOURA'

print('\nJO   ')
sleep(2)
print('  KEM')
sleep(2)
print('     PÔ')
sleep(1)

if cpu == 'PEDRA':
  if player == 'PEDRA':
    print(f'\nCPU escolheu {cpu} e PLAYER escolheu {player}. EMPATE!!!')
  elif player == 'PAPEL':
    print(f'\nCPU escolheu {cpu} e PLAYER escolheu {player}. PLAYER WINS!!!')
  else:
    print(f'\nCPU escolheu {cpu} e PLAYER escolheu {player}. CPU WINS!!!')
elif cpu == 'PAPEL':
  if player == 'PEDRA':
    print(f'\nCPU escolheu {cpu} e PLAYER escolheu {player}. CPU WINS!!!')
  elif player == 'PAPEL':
    print(f'\nCPU escolheu {cpu} e PLAYER escolheu {player}. EMPATE!!!')
  else:
    print(f'\nCPU escolheu {cpu} e PLAYER escolheu {player}. PLAYER WINS!!!')
else:
  if player == 'PEDRA':
    print(f'\nCPU escolheu {cpu} e PLAYER escolheu {player}. PLAYER EMPATE!!!')
  elif player == 'PAPEL':
    print(f'\nCPU escolheu {cpu} e PLAYER escolheu {player}. CPU WINS!!!')
  else:
    print(f'\nCPU escolheu {cpu} e PLAYER escolheu {player}. EMPATE!!!')